# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtui\mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1523, 576)
        MainWindow.setStyleSheet(_fromUtf8("QLabel[notification=\"major\"] {\n"
"    font: 28pt \"Helvetica\";\n"
"    font-weight: bold;\n"
"    qproperty-alignment: AlignCenter;\n"
"    border: 8px solid black;\n"
"    border-radius: 15px;\n"
"}\n"
""))
        self.main_widget = QtGui.QWidget(MainWindow)
        self.main_widget.setObjectName(_fromUtf8("main_widget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.main_widget)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.h_layout_main = QtGui.QHBoxLayout()
        self.h_layout_main.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.h_layout_main.setSpacing(0)
        self.h_layout_main.setObjectName(_fromUtf8("h_layout_main"))
        self.tab_widget = MainTabView(self.main_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_widget.sizePolicy().hasHeightForWidth())
        self.tab_widget.setSizePolicy(sizePolicy)
        self.tab_widget.setTabPosition(QtGui.QTabWidget.North)
        self.tab_widget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_widget.setElideMode(QtCore.Qt.ElideRight)
        self.tab_widget.setDocumentMode(False)
        self.tab_widget.setTabsClosable(False)
        self.tab_widget.setObjectName(_fromUtf8("tab_widget"))
        self.tab_files = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_files.sizePolicy().hasHeightForWidth())
        self.tab_files.setSizePolicy(sizePolicy)
        self.tab_files.setObjectName(_fromUtf8("tab_files"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_files)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.stacked_main = QtGui.QStackedWidget(self.tab_files)
        self.stacked_main.setMinimumSize(QtCore.QSize(100, 100))
        self.stacked_main.setObjectName(_fromUtf8("stacked_main"))
        self.page_add_files = QtGui.QWidget()
        self.page_add_files.setObjectName(_fromUtf8("page_add_files"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_add_files)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.label = QtGui.QLabel(self.page_add_files)
        self.label.setMinimumSize(QtCore.QSize(0, 55))
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setProperty("notification", _fromUtf8("major"))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.widget_add_files = QtGui.QWidget(self.page_add_files)
        self.widget_add_files.setMinimumSize(QtCore.QSize(250, 310))
        self.widget_add_files.setMaximumSize(QtCore.QSize(286, 433))
        self.widget_add_files.setStyleSheet(_fromUtf8("image: url(:/images/addfile.png);\n"
"position: center center;"))
        self.widget_add_files.setObjectName(_fromUtf8("widget_add_files"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_add_files)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_4.addWidget(self.widget_add_files)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.stacked_main.addWidget(self.page_add_files)
        self.page_validate = QtGui.QWidget()
        self.page_validate.setObjectName(_fromUtf8("page_validate"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.page_validate)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.group_files = QtGui.QGroupBox(self.page_validate)
        self.group_files.setObjectName(_fromUtf8("group_files"))
        self.verticalLayout = QtGui.QVBoxLayout(self.group_files)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.table_files = FilesTableView(self.group_files)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_files.sizePolicy().hasHeightForWidth())
        self.table_files.setSizePolicy(sizePolicy)
        self.table_files.setFrameShadow(QtGui.QFrame.Plain)
        self.table_files.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_files.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_files.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.table_files.setObjectName(_fromUtf8("table_files"))
        self.table_files.horizontalHeader().setVisible(True)
        self.verticalLayout.addWidget(self.table_files)
        self.horizontalLayout.addWidget(self.group_files)
        self.v_layout_right = QtGui.QVBoxLayout()
        self.v_layout_right.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.v_layout_right.setContentsMargins(-1, -1, -1, 0)
        self.v_layout_right.setObjectName(_fromUtf8("v_layout_right"))
        self.group_actions = QtGui.QGroupBox(self.page_validate)
        self.group_actions.setMaximumSize(QtCore.QSize(200, 16777215))
        self.group_actions.setObjectName(_fromUtf8("group_actions"))
        self.formLayout_2 = QtGui.QFormLayout(self.group_actions)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.btn_validate = QtGui.QPushButton(self.group_actions)
        self.btn_validate.setAutoDefault(False)
        self.btn_validate.setDefault(False)
        self.btn_validate.setFlat(False)
        self.btn_validate.setObjectName(_fromUtf8("btn_validate"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.btn_validate)
        self.btn_clear = QtGui.QPushButton(self.group_actions)
        self.btn_clear.setObjectName(_fromUtf8("btn_clear"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.SpanningRole, self.btn_clear)
        self.v_layout_right.addWidget(self.group_actions)
        self.group_options = QtGui.QGroupBox(self.page_validate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_options.sizePolicy().hasHeightForWidth())
        self.group_options.setSizePolicy(sizePolicy)
        self.group_options.setMinimumSize(QtCore.QSize(200, 200))
        self.group_options.setMaximumSize(QtCore.QSize(50, 16777215))
        self.group_options.setObjectName(_fromUtf8("group_options"))
        self.formLayout = QtGui.QFormLayout(self.group_options)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.check_best_practices = QtGui.QCheckBox(self.group_options)
        self.check_best_practices.setObjectName(_fromUtf8("check_best_practices"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.check_best_practices)
        self.check_profile = QtGui.QCheckBox(self.group_options)
        self.check_profile.setEnabled(False)
        self.check_profile.setObjectName(_fromUtf8("check_profile"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.check_profile)
        self.check_external_schemas = QtGui.QCheckBox(self.group_options)
        self.check_external_schemas.setEnabled(False)
        self.check_external_schemas.setObjectName(_fromUtf8("check_external_schemas"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.check_external_schemas)
        self.v_layout_right.addWidget(self.group_options)
        self.progress_validation = QtGui.QProgressBar(self.page_validate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_validation.sizePolicy().hasHeightForWidth())
        self.progress_validation.setSizePolicy(sizePolicy)
        self.progress_validation.setMaximumSize(QtCore.QSize(200, 16777215))
        self.progress_validation.setProperty("value", 0)
        self.progress_validation.setObjectName(_fromUtf8("progress_validation"))
        self.v_layout_right.addWidget(self.progress_validation)
        self.horizontalLayout.addLayout(self.v_layout_right)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.stacked_main.addWidget(self.page_validate)
        self.horizontalLayout_2.addWidget(self.stacked_main)
        self.tab_widget.addTab(self.tab_files, _fromUtf8(""))
        self.tab_remove = QtGui.QWidget()
        self.tab_remove.setEnabled(False)
        self.tab_remove.setObjectName(_fromUtf8("tab_remove"))
        self.tab_widget.addTab(self.tab_remove, _fromUtf8(""))
        self.h_layout_main.addWidget(self.tab_widget)
        self.horizontalLayout_6.addLayout(self.h_layout_main)
        MainWindow.setCentralWidget(self.main_widget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1523, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_file = QtGui.QMenu(self.menubar)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        self.menu_options = QtGui.QMenu(self.menubar)
        self.menu_options.setObjectName(_fromUtf8("menu_options"))
        self.menu_xml_schema = QtGui.QMenu(self.menu_options)
        self.menu_xml_schema.setObjectName(_fromUtf8("menu_xml_schema"))
        self.menu_stix_profile = QtGui.QMenu(self.menu_options)
        self.menu_stix_profile.setObjectName(_fromUtf8("menu_stix_profile"))
        MainWindow.setMenuBar(self.menubar)
        self.status_bar = QtGui.QStatusBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_bar.sizePolicy().hasHeightForWidth())
        self.status_bar.setSizePolicy(sizePolicy)
        self.status_bar.setMinimumSize(QtCore.QSize(0, 0))
        self.status_bar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.status_bar.setObjectName(_fromUtf8("status_bar"))
        MainWindow.setStatusBar(self.status_bar)
        self.action_add_file = QtGui.QAction(MainWindow)
        self.action_add_file.setObjectName(_fromUtf8("action_add_file"))
        self.action_about = QtGui.QAction(MainWindow)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action_set_schema_dir = QtGui.QAction(MainWindow)
        self.action_set_schema_dir.setObjectName(_fromUtf8("action_set_schema_dir"))
        self.actionEnable = QtGui.QAction(MainWindow)
        self.actionEnable.setObjectName(_fromUtf8("actionEnable"))
        self.action_set_stix_profile = QtGui.QAction(MainWindow)
        self.action_set_stix_profile.setObjectName(_fromUtf8("action_set_stix_profile"))
        self.action_enable_all_profile = QtGui.QAction(MainWindow)
        self.action_enable_all_profile.setObjectName(_fromUtf8("action_enable_all_profile"))
        self.action_disable_all_profile = QtGui.QAction(MainWindow)
        self.action_disable_all_profile.setObjectName(_fromUtf8("action_disable_all_profile"))
        self.action_enable_all_best_practice = QtGui.QAction(MainWindow)
        self.action_enable_all_best_practice.setObjectName(_fromUtf8("action_enable_all_best_practice"))
        self.action_disable_all_best_practice = QtGui.QAction(MainWindow)
        self.action_disable_all_best_practice.setObjectName(_fromUtf8("action_disable_all_best_practice"))
        self.action_use_builtin_schemas = QtGui.QAction(MainWindow)
        self.action_use_builtin_schemas.setCheckable(True)
        self.action_use_builtin_schemas.setChecked(True)
        self.action_use_builtin_schemas.setEnabled(True)
        self.action_use_builtin_schemas.setIconVisibleInMenu(False)
        self.action_use_builtin_schemas.setObjectName(_fromUtf8("action_use_builtin_schemas"))
        self.action_add_directory_2 = QtGui.QAction(MainWindow)
        self.action_add_directory_2.setObjectName(_fromUtf8("action_add_directory_2"))
        self.action_add_directory = QtGui.QAction(MainWindow)
        self.action_add_directory.setObjectName(_fromUtf8("action_add_directory"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.menu_file.addAction(self.action_add_file)
        self.menu_file.addAction(self.action_add_directory)
        self.menu_help.addAction(self.action_about)
        self.menu_xml_schema.addAction(self.action_set_schema_dir)
        self.menu_stix_profile.addAction(self.action_set_stix_profile)
        self.menu_options.addAction(self.menu_xml_schema.menuAction())
        self.menu_options.addAction(self.menu_stix_profile.menuAction())
        self.menu_options.addAction(self.actionSettings)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_options.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        self.stacked_main.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "STIX Document Validator", None))
        self.label.setText(_translate("MainWindow", "Add Files...", None))
        self.group_files.setTitle(_translate("MainWindow", "Validate Files", None))
        self.group_actions.setTitle(_translate("MainWindow", "Actions", None))
        self.btn_validate.setText(_translate("MainWindow", "Validate", None))
        self.btn_clear.setText(_translate("MainWindow", "Clear Files", None))
        self.group_options.setTitle(_translate("MainWindow", "Options", None))
        self.check_best_practices.setText(_translate("MainWindow", "Validate Best Practices", None))
        self.check_profile.setText(_translate("MainWindow", "Valdiate STIX Profile", None))
        self.check_external_schemas.setText(_translate("MainWindow", "External Schemas", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_files), _translate("MainWindow", "Documents", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_remove), _translate("MainWindow", "Tab 2", None))
        self.menu_file.setTitle(_translate("MainWindow", "File", None))
        self.menu_help.setTitle(_translate("MainWindow", "Help", None))
        self.menu_options.setTitle(_translate("MainWindow", "Options", None))
        self.menu_xml_schema.setTitle(_translate("MainWindow", "XML Schema", None))
        self.menu_stix_profile.setTitle(_translate("MainWindow", "STIX Profile", None))
        self.action_add_file.setText(_translate("MainWindow", "Add Files...", None))
        self.action_add_file.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.action_about.setText(_translate("MainWindow", "About...", None))
        self.action_set_schema_dir.setText(_translate("MainWindow", "Set Schema Diectory", None))
        self.action_set_schema_dir.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionEnable.setText(_translate("MainWindow", "Enable", None))
        self.action_set_stix_profile.setText(_translate("MainWindow", "Set STIX Profile", None))
        self.action_set_stix_profile.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.action_enable_all_profile.setText(_translate("MainWindow", "Enable All", None))
        self.action_disable_all_profile.setText(_translate("MainWindow", "Disable All", None))
        self.action_enable_all_best_practice.setText(_translate("MainWindow", "Enable All", None))
        self.action_disable_all_best_practice.setText(_translate("MainWindow", "Disable All", None))
        self.action_use_builtin_schemas.setText(_translate("MainWindow", "Use Builtin Schemas", None))
        self.action_add_directory_2.setText(_translate("MainWindow", "Add Directory...", None))
        self.action_add_directory.setText(_translate("MainWindow", "Add Directory...", None))
        self.action_add_directory.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings...", None))

from cutiestix.widgets import FilesTableView, MainTabView
import images_rc
